# Generated by Django 5.2.3 on 2025-07-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catharsis", "0002_delete_questionnaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_group", models.CharField(max_length=50)),
                ("gender_identity", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                ("stress_level", models.CharField(max_length=10)),
                ("peer_support_availability", models.CharField(max_length=50)),
                ("comfort_level", models.CharField(max_length=50)),
                ("stress_sources", models.CharField(max_length=100)),
                ("used_peer_support", models.CharField(max_length=10)),
                ("reason_not_seeking", models.TextField(blank=True)),
                ("societal_stance", models.CharField(max_length=100)),
                ("desired_features", models.TextField()),
                ("opinion_on_app", models.CharField(max_length=50)),
            ],
        ),
    ]
