# Generated by Django 5.2.3 on 2025-07-06 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catharsis", "0004_thread_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="user",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
